#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# reload X settings
xrdb -merge ~/.Xresources &

# start network manager applet
nm-applet &

# use xbindkeys
xbindkeys

# xcompmgr sets bg to ugly gray, so explicitly set bg color
hsetroot -solid "#000000"

# for shadow and opacity in X.org
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 -f -D5 &

# Start the VirtualBox sharing services
VBoxClient-all &

# Keymapping
xmodmap -e "keycode 96 = Insert Insert"

# set wallpaper
exec feh --bg-scale ~/Pictures/wallpaper.jpg &

exec i3
